version: "3"
 
services:
    
  php:
    image: php:7-apache
    volumes:
      # Montamos nuestra web desde fuera en el directorio web del contenedor
      - ./src:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/user/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/user/local/etc/php/conf.d/error_reporting.ini
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    ports:
      - 8010:80

  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - 3306:3306
    environment:
        MYSQL_DATABASE: assignment_tracker
        MYSQL_USER: sample #additional user and password, can access with root | example
        MYSQL_PASSWORD: sample
        MYSQL_ROOT_PASSWORD: example
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - 8020:80
    links: 
      - db:db