name: CI PHPUnit and Puppeteer

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.4]
        dependency-version: [prefer-stable]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: composer update
    - run: composer install # or alternative dependency management
    # ... then your own project steps ...
    - run: echo "Running PHPUnit tests..."
    - run: phpunit ./src/tests/phpunit/
    - run: |
        echo "Running docker-compose"
        docker-compose up -d
        echo "Running Puppeteer tests..."
        npm install puppeteer
        node tests/puppeteer/example.js