name: CI PHPUnit and Puppeteer

on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  php-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.4]
        dependency-version: [prefer-stable]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@master
      with:
        version: 10.x
    - name: npm install
      run: npm install
    - name: Run PHPUnit tests
      run: phpunit . --coverage-clover cov/clover.xml --whitelist=Sample.php 
    - name: Upload coverage results to Coveralls
      run: |
        composer global require php-coveralls/php-coveralls
        sleep 20
        cd src/tests/phpunit
        php-coveralls --coverage_clover=cov/clover.xml -v
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  puppeteer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.4]
        dependency-version: [prefer-stable]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: composer update
    - run: composer install
    - name: Run App and DB
      run: |
        docker-compose up -d 
        .github/workflows/installDB.sh

    - name: Run Tests
      run: |
        sudo apt install mysql-server
        echo "Running Puppeteer tests..."
        npm install puppeteer
        cd src/tests
        node puppeteer/example.js
      #es importante hacer el node desde la carpeta tests porque si no, el tests no coge bien la ruta para guardar las screenshots
#  finish:
#    needs: [php-unit-tests]
#    runs-on: ubuntu-latest
#    steps:
#    - name: Coveralls Finished
#      uses: coverallsapp/github-action@master
#      with:
#        parallel-finished: true
#      env:
#        github-token: ${{ secrets.GITHUB_TOKEN }} #el toquen lo da automaticamente github, no hace falta ponerlo por ningun lado
        