name: CI phpunit test

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.4]
        dependency-version: [prefer-stable]

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none
    - run: composer install # or alternative dependency management
    - uses: php-actions/phpunit@v3
    # ... then your own project steps ...
    - run: echo "Running tests..."
    - run: phpunit ./src/tests/phpunit/